# Generated by Django 5.0.2 on 2024-11-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=320)),
                ('contraseña', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('horas_disponibles', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('duracion', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='citasApp.usuario')),
            ],
            bases=('citasApp.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='citasApp.usuario')),
                ('telefono', models.CharField(max_length=15)),
            ],
            bases=('citasApp.usuario',),
        ),
        migrations.CreateModel(
            name='Estilista',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='citasApp.usuario')),
                ('especialidades', models.CharField(max_length=1000)),
                ('horario', models.JSONField()),
            ],
            bases=('citasApp.usuario',),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('Reservada', 'Reservada'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], max_length=20)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citasApp.servicio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citasApp.cliente')),
                ('estilista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citasApp.estilista')),
            ],
        ),
    ]
